---
# tasks file for install_open_vmware_tools

- name: debian | installing open-vm-tools if a VM
  apt: name=open-vm-tools state=latest
  when: ansible_os_family == "Debian" and ansible_virtualization_type == "VMware"
  tags:
    - install
    - update

- name: centos | installing open-vm-tools if a VM
  yum: name=open-vm-tools state=latest
  when: ansible_os_family == "RedHat" and ansible_virtualization_type == "VMware"
  tags:
    - install
    - update

- name: centos | starting and enabling open-vm-tools
  service: name=vmtoolsd.service state=restarted enabled=yes
  when: ansible_os_family == "RedHat" and ansible_virtualization_type == "VMware"
  tags:
    - install
    - update
    - configure
